/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pin_mux.c
**     Project     : mod1
**     Processor   : MKL25Z128VLK4
**     Component   : PinSettings
**     Version     : Component 1.2.0, Driver 1.4, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-10-09, 07:54, # CodeGen: 1
**     Abstract    :
**
**     Settings    :
**          Component name                                 : pin_mux
**          PinSettings IP Block                           : PinSettings
**          Processor                                      : MKL25Z128LK4_4SDK
**          Pin settings                                   : 
**            Routing                                      : 
**              Peripheral Type ADC                        : 
**                Custom name                              : ADC0
**                ADC0                                     : 
**                  DM0 - Minus channel 0                  : <Automatic>
**                  DM3 - Minus channel 3                  : <Automatic>
**                  DP0 - Plus channel 0                   : <Automatic>
**                  DP3 - Plus channel 3                   : <Automatic>
**                  SE0 - Single-ended channel 0           : <Automatic>
**                  SE3 - Single-ended channel 3           : <Automatic>
**                  SE8 - Single-ended channel 8           : <Automatic>
**                  SE9 - Single-ended channel 9           : <Automatic>
**                  SE11 - Single-ended channel 11         : <Automatic>
**                  SE12 - Single-ended channel 12         : <Automatic>
**                  SE13 - Single-ended channel 13         : <Automatic>
**                  SE14 - Single-ended channel 14         : <Automatic>
**                  SE15 - Single-ended channel 15         : <Automatic>
**                  SE23 - Single-ended channel 23         : <Automatic>
**                  SE4a - Single-ended channel 4a         : <Automatic>
**                  SE7a - Single-ended channel 7a         : <Automatic>
**                  SE4b - Single-ended channel 4a         : <Automatic>
**                  SE5b - Single-ended channel 5a         : <Automatic>
**                  SE6b - Single-ended channel 6a         : <Automatic>
**                  SE7b - Single-ended channel 7a         : <Automatic>
**                  Trigger A input                        : <Automatic>
**                  Trigger B input                        : <Automatic>
**                  Voltage reference high                 : VDDA
**                  Voltage reference high                 : VREFH
**                  Voltage reference low                  : VREFL
**                  Voltage reference low                  : VSSA
**                Bool_ADC0                                : yes
**              Peripheral Type BP                         : 
**              Peripheral Type CMP                        : 
**                Custom name                              : CMP0
**                CMP0                                     : 
**                  IN0 - Input 0                          : <Automatic>
**                  IN1 - Input 1                          : <Automatic>
**                  IN2 - Input 2                          : <Automatic>
**                  IN3 - Input 3                          : <Automatic>
**                  IN4 - Input 4                          : <Automatic>
**                  IN5 - Input 5                          : <Automatic>
**                  OUT - Comparator output                : <Automatic>
**                Bool_CMP0                                : yes
**              Peripheral Type CoreDebug                  : 
**                Custom name                              : CoreDebug
**              Peripheral Type DAC                        : 
**                Custom name                              : DAC0
**                DAC0                                     : 
**                  Output pin                             : <Automatic>
**                Bool_DAC0                                : yes
**              Peripheral Type DMA                        : 
**                Custom name                              : DMA
**              Peripheral Type DMAMUX                     : 
**                Custom name                              : DMAMUX0
**              Peripheral Type DWT                        : 
**              Peripheral Type FGPIO                      : 
**              Peripheral Type FTFA                       : 
**                Custom name                              : FTFA
**              Peripheral Type GPIO                       : 
**                Custom name                              : GPIOA
**                GPIOA                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 12                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 13                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 14                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 15                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 16                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 17                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 18                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 19                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 20                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOA                               : yes
**                Custom name                              : GPIOB
**                GPIOB                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 8                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 9                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 10                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 11                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 16                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 17                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 18                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 19                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOB                               : yes
**                Custom name                              : GPIOC
**                GPIOC                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 6                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 7                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 8                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 9                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 10                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 11                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 12                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 13                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 16                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 17                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOC                               : yes
**                Custom name                              : GPIOD
**                GPIOD                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 6                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 7                                  : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOD                               : yes
**                Custom name                              : GPIOE
**                GPIOE                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 20                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 21                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 22                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 23                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 24                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 25                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 29                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 30                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 31                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOE                               : yes
**              Peripheral Type I2C                        : 
**                Custom name                              : I2C0
**                I2C0                                     : 
**                  SCL - Serial clock                     : <Automatic>
**                  SDA - Serial data                      : <Automatic>
**                Bool_I2C0                                : yes
**                Custom name                              : I2C1
**                I2C1                                     : 
**                  SCL - Serial clock                     : <Automatic>
**                  SDA - Serial data                      : <Automatic>
**                Bool_I2C1                                : yes
**              Peripheral Type LCD                        : 
**              Peripheral Type LLWU                       : 
**                Custom name                              : LLWU
**                LLWU                                     : 
**                  P5 - Wake-up pin 5                     : <Automatic>
**                  P6 - Wake-up pin 6                     : <Automatic>
**                  P7 - Wake-up pin 7                     : <Automatic>
**                  P8 - Wake-up pin 8                     : <Automatic>
**                  P9 - Wake-up pin 9                     : <Automatic>
**                  P10 - Wake-up pin 10                   : <Automatic>
**                  P14 - Wake-up pin 14                   : <Automatic>
**                  P15 - Wake-up pin 15                   : <Automatic>
**                Bool_LLWU                                : yes
**              Peripheral Type LPTMR                      : 
**                Custom name                              : LPTMR0
**                LPTMR0                                   : 
**                  Pulse counter input 0                  : <Automatic>
**                  Pulse counter input 1                  : <Automatic>
**                  Pulse counter input 2                  : <Automatic>
**                Bool_LPTMR0                              : yes
**              Peripheral Type MCG                        : 
**                Custom name                              : MCG
**              Peripheral Type MCM                        : 
**                Custom name                              : MCM
**              Peripheral Type MTB                        : 
**              Peripheral Type MTBDWT                     : 
**              Peripheral Type NV                         : 
**                Custom name                              : FTFA_FlashConfig
**              Peripheral Type NVIC                       : 
**                Custom name                              : NVIC
**              Peripheral Type OSC                        : 
**                Custom name                              : OSC0
**                OSC0                                     : 
**                  External clock/oscillator input        : <Automatic>
**                  Oscillator output                      : <Automatic>
**                Bool_OSC0                                : yes
**              Peripheral Type PIT                        : 
**                Custom name                              : PIT
**              Peripheral Type PMC                        : 
**                Custom name                              : PMC
**              Peripheral Type PORT                       : 
**                Custom name                              : PORTA
**                Custom name                              : PORTB
**                Custom name                              : PORTC
**                Custom name                              : PORTD
**                Custom name                              : PORTE
**              Peripheral Type RCM                        : 
**                Custom name                              : RCM
**                RCM                                      : 
**                  Reset input                            : <Automatic>
**                Bool_RCM                                 : yes
**              Peripheral Type ROM                        : 
**              Peripheral Type RTC                        : 
**                Custom name                              : RTC
**                RTC                                      : 
**                  Clock input                            : <Automatic>
**                  Oscillator output                      : <Automatic>
**                Bool_RTC                                 : yes
**              Peripheral Type SCB                        : 
**                Custom name                              : SystemControl
**                SystemControl                            : 
**                  NMI - Non-maskable interrupt           : <Automatic>
**                Bool_SystemControl                       : yes
**              Peripheral Type SIM                        : 
**                Custom name                              : SIM
**                SIM                                      : 
**                  MCG clock output                       : <Automatic>
**                Bool_SIM                                 : yes
**              Peripheral Type SMC                        : 
**                Custom name                              : SMC
**              Peripheral Type SPI                        : 
**                Custom name                              : SPI0
**                SPI0                                     : 
**                  SPI peripheral chip select(output) 0 or slave select(input): <Automatic>
**                  Direction                              : <Automatic>
**                  MISO - Master input/Slave output       : <Automatic>
**                  Direction                              : <Automatic>
**                  Master data output and slave data input: <Automatic>
**                  Direction                              : <Automatic>
**                  SCK - Serial clock                     : <Automatic>
**                  Direction                              : <Automatic>
**                  Peripheral chip select 0               : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_SPI0                                : yes
**                Custom name                              : SPI1
**                SPI1                                     : 
**                  SPI peripheral chip select(output) 0 or slave select(input): <Automatic>
**                  Direction                              : <Automatic>
**                  MISO - Master input/Slave output       : <Automatic>
**                  Direction                              : <Automatic>
**                  Master data output and slave data input: <Automatic>
**                  Direction                              : <Automatic>
**                  SCK - Serial clock                     : <Automatic>
**                  Direction                              : <Automatic>
**                  Peripheral chip select 0               : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_SPI1                                : yes
**              Peripheral Type SUPPLY                     : 
**                SUPPLY                                   : 
**                  Chip power supply                      : VDD8
**                  Chip power supply                      : VDD48
**                  Chip power supply                      : VDD75
**                  Analog power supply                    : VDDA
**                  Chip power ground                      : VSS9
**                  Chip power ground                      : VSS49
**                  Chip power ground                      : VSS74
**                  Analog ground                          : VSSA
**                Bool_SUPPLY                              : yes
**              Peripheral Type SWD                        : 
**                SWD                                      : 
**                  CLK - Clock                            : <Automatic>
**                  DIO - Data                             : <Automatic>
**                Bool_SWD                                 : yes
**              Peripheral Type SysTick                    : 
**                Custom name                              : SysTick
**              Peripheral Type TPM                        : 
**                Custom name                              : TPM0
**                TPM0                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH2 - Channel 2                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH3 - Channel 3                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH4 - Channel 4                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH5 - Channel 5                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN - External clock input           : <Automatic>
**                Bool_TPM0                                : yes
**                Custom name                              : TPM1
**                TPM1                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN - External clock input           : <Automatic>
**                Bool_TPM1                                : yes
**                Custom name                              : TPM2
**                TPM2                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN - External clock input           : <Automatic>
**                Bool_TPM2                                : yes
**              Peripheral Type TSI                        : 
**                Custom name                              : TSI0
**                TSI0                                     : 
**                  Channel 0 sensing                      : <Automatic>
**                  Channel 1 sensing                      : <Automatic>
**                  Channel 2 sensing                      : <Automatic>
**                  Channel 3 sensing                      : <Automatic>
**                  Channel 4 sensing                      : <Automatic>
**                  Channel 5 sensing                      : <Automatic>
**                  Channel 6 sensing                      : <Automatic>
**                  Channel 7 sensing                      : <Automatic>
**                  Channel 8 sensing                      : <Automatic>
**                  Channel 9 sensing                      : <Automatic>
**                  Channel 10 sensing                     : <Automatic>
**                  Channel 11 sensing                     : <Automatic>
**                  Channel 12 sensing                     : <Automatic>
**                  Channel 13 sensing                     : <Automatic>
**                  Channel 14 sensing                     : <Automatic>
**                  Channel 15 sensing                     : <Automatic>
**                Bool_TSI0                                : yes
**              Peripheral Type UART                       : 
**                Custom name                              : UART1
**                UART1                                    : 
**                  RX - Receive data                      : <Automatic>
**                  TX - Transmit data                     : <Automatic>
**                Bool_UART1                               : yes
**                Custom name                              : UART2
**                UART2                                    : 
**                  RX - Receive data                      : <Automatic>
**                  TX - Transmit data                     : <Automatic>
**                Bool_UART2                               : yes
**              Peripheral Type UART0                      : 
**                Custom name                              : UART0
**                UART0                                    : 
**                  RX - Receive data                      : TSI0_CH2/PTA1/UART0_RX/TPM2_CH0
**                  TX - Transmit data                     : TSI0_CH3/PTA2/UART0_TX/TPM2_CH1
**                Bool_UART0                               : yes
**              Peripheral Type USB                        : 
**                Custom name                              : USB0
**                USB0                                     : 
**                  CLKIN - Alternate Clock                : <Automatic>
**                  DM - Data minus                        : USB0_DM
**                  DP - Data plus                         : USB0_DP
**                  Regulator output voltage               : VOUT33
**                  Unregulated power supply               : VREGIN
**                Bool_USB0                                : yes
**              Non-peripheral pins                        : 
**            Electrical properties                        : 
**              Pin 1: PTE0/UART1_TX/RTC_CLKOUT/CMP0_OUT/I2C1_SDA: 
**                Custom name, Signal name                 : PTE0/UART1_TX/RTC_CLKOUT/CMP0_OUT/I2C1_SDA
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 2: PTE1/SPI1_MOSI/UART1_RX/SPI1_MISO/I2C1_SCL: 
**                Custom name, Signal name                 : PTE1/SPI1_MOSI/UART1_RX/SPI1_MISO/I2C1_SCL
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 3: PTE2/SPI1_SCK                       : 
**                Custom name, Signal name                 : PTE2/SPI1_SCK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 4: PTE3/SPI1_MISO/SPI1_MOSI            : 
**                Custom name, Signal name                 : PTE3/SPI1_MISO/SPI1_MOSI
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 5: PTE4/SPI1_PCS0                      : 
**                Custom name, Signal name                 : PTE4/SPI1_PCS0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 6: PTE5                                : 
**                Custom name, Signal name                 : PTE5
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 7: VDD8                                : 
**                Custom name, Signal name                 : VDD8
**              Pin 8: VSS9                                : 
**                Custom name, Signal name                 : VSS9
**              Pin 9: USB0_DP                             : 
**                Custom name, Signal name                 : USB0_DP
**              Pin 10: USB0_DM                            : 
**                Custom name, Signal name                 : USB0_DM
**              Pin 11: VOUT33                             : 
**                Custom name, Signal name                 : VOUT33
**              Pin 12: VREGIN                             : 
**                Custom name, Signal name                 : VREGIN
**              Pin 13: ADC0_DP0/ADC0_SE0/PTE20/TPM1_CH0/UART0_TX: 
**                Custom name, Signal name                 : ADC0_DP0/ADC0_SE0/PTE20/TPM1_CH0/UART0_TX
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 14: ADC0_DM0/ADC0_SE4a/PTE21/TPM1_CH1/UART0_RX: 
**                Custom name, Signal name                 : ADC0_DM0/ADC0_SE4a/PTE21/TPM1_CH1/UART0_RX
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 15: ADC0_DP3/ADC0_SE3/PTE22/TPM2_CH0/UART2_TX: 
**                Custom name, Signal name                 : ADC0_DP3/ADC0_SE3/PTE22/TPM2_CH0/UART2_TX
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 16: ADC0_DM3/ADC0_SE7a/PTE23/TPM2_CH1/UART2_RX: 
**                Custom name, Signal name                 : ADC0_DM3/ADC0_SE7a/PTE23/TPM2_CH1/UART2_RX
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 17: VDDA                               : 
**                Custom name, Signal name                 : VDDA
**              Pin 18: VREFH                              : 
**                Custom name, Signal name                 : VREFH
**              Pin 19: VREFL                              : 
**                Custom name, Signal name                 : VREFL
**              Pin 20: VSSA                               : 
**                Custom name, Signal name                 : VSSA
**              Pin 21: CMP0_IN5/ADC0_SE4b/PTE29/TPM0_CH2/TPM_CLKIN0: 
**                Custom name, Signal name                 : CMP0_IN5/ADC0_SE4b/PTE29/TPM0_CH2/TPM_CLKIN0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 22: DAC0_OUT/ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1: 
**                Custom name, Signal name                 : DAC0_OUT/ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 23: PTE31/TPM0_CH4                     : 
**                Custom name, Signal name                 : PTE31/TPM0_CH4
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 24: PTE24/TPM0_CH0/I2C0_SCL            : 
**                Custom name, Signal name                 : PTE24/TPM0_CH0/I2C0_SCL
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 25: PTE25/TPM0_CH1/I2C0_SDA            : 
**                Custom name, Signal name                 : PTE25/TPM0_CH1/I2C0_SDA
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 26: TSI0_CH1/PTA0/TPM0_CH5/SWD_CLK     : 
**                Custom name, Signal name                 : TSI0_CH1/PTA0/TPM0_CH5/SWD_CLK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 27: TSI0_CH2/PTA1/UART0_RX/TPM2_CH0    : 
**                Custom name, Signal name                 : TSI0_CH2/PTA1/UART0_RX/TPM2_CH0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 28: TSI0_CH3/PTA2/UART0_TX/TPM2_CH1    : 
**                Custom name, Signal name                 : TSI0_CH3/PTA2/UART0_TX/TPM2_CH1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 29: TSI0_CH4/PTA3/I2C1_SCL/TPM0_CH0/SWD_DIO: 
**                Custom name, Signal name                 : TSI0_CH4/PTA3/I2C1_SCL/TPM0_CH0/SWD_DIO
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 30: TSI0_CH5/PTA4/I2C1_SDA/TPM0_CH1/NMI_b: 
**                Custom name, Signal name                 : TSI0_CH5/PTA4/I2C1_SDA/TPM0_CH1/NMI_b
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 31: PTA5/USB_CLKIN/TPM0_CH2            : 
**                Custom name, Signal name                 : PTA5/USB_CLKIN/TPM0_CH2
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 32: PTA12/TPM1_CH0                     : 
**                Custom name, Signal name                 : PTA12/TPM1_CH0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 33: PTA13/TPM1_CH1                     : 
**                Custom name, Signal name                 : PTA13/TPM1_CH1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 34: PTA14/SPI0_PCS0/UART0_TX           : 
**                Custom name, Signal name                 : PTA14/SPI0_PCS0/UART0_TX
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 35: PTA15/SPI0_SCK/UART0_RX            : 
**                Custom name, Signal name                 : PTA15/SPI0_SCK/UART0_RX
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 36: PTA16/SPI0_MOSI/SPI0_MISO          : 
**                Custom name, Signal name                 : PTA16/SPI0_MOSI/SPI0_MISO
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 37: PTA17/SPI0_MISO/SPI0_MOSI          : 
**                Custom name, Signal name                 : PTA17/SPI0_MISO/SPI0_MOSI
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 38: VDD48                              : 
**                Custom name, Signal name                 : VDD48
**              Pin 39: VSS49                              : 
**                Custom name, Signal name                 : VSS49
**              Pin 40: EXTAL0/PTA18/UART1_RX/TPM_CLKIN0   : 
**                Custom name, Signal name                 : EXTAL0/PTA18/UART1_RX/TPM_CLKIN0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 41: XTAL0/PTA19/UART1_TX/TPM_CLKIN1/LPTMR0_ALT1: 
**                Custom name, Signal name                 : XTAL0/PTA19/UART1_TX/TPM_CLKIN1/LPTMR0_ALT1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 42: PTA20/RESET_b                      : 
**                Custom name, Signal name                 : PTA20/RESET_b
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 43: ADC0_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0: 
**                Custom name, Signal name                 : ADC0_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 44: ADC0_SE9/TSI0_CH6/PTB1/I2C0_SDA/TPM1_CH1: 
**                Custom name, Signal name                 : ADC0_SE9/TSI0_CH6/PTB1/I2C0_SDA/TPM1_CH1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 45: ADC0_SE12/TSI0_CH7/PTB2/I2C0_SCL/TPM2_CH0: 
**                Custom name, Signal name                 : ADC0_SE12/TSI0_CH7/PTB2/I2C0_SCL/TPM2_CH0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 46: ADC0_SE13/TSI0_CH8/PTB3/I2C0_SDA/TPM2_CH1: 
**                Custom name, Signal name                 : ADC0_SE13/TSI0_CH8/PTB3/I2C0_SDA/TPM2_CH1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 47: PTB8/EXTRG_IN                      : 
**                Custom name, Signal name                 : PTB8/EXTRG_IN
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 48: PTB9                               : 
**                Custom name, Signal name                 : PTB9
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 49: PTB10/SPI1_PCS0                    : 
**                Custom name, Signal name                 : PTB10/SPI1_PCS0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 50: PTB11/SPI1_SCK                     : 
**                Custom name, Signal name                 : PTB11/SPI1_SCK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 51: TSI0_CH9/PTB16/SPI1_MOSI/UART0_RX/TPM_CLKIN0/SPI1_MISO: 
**                Custom name, Signal name                 : TSI0_CH9/PTB16/SPI1_MOSI/UART0_RX/TPM_CLKIN0/SPI1_MISO
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 52: TSI0_CH10/PTB17/SPI1_MISO/UART0_TX/TPM_CLKIN1/SPI1_MOSI: 
**                Custom name, Signal name                 : TSI0_CH10/PTB17/SPI1_MISO/UART0_TX/TPM_CLKIN1/SPI1_MOSI
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 53: TSI0_CH11/PTB18/TPM2_CH0           : 
**                Custom name, Signal name                 : TSI0_CH11/PTB18/TPM2_CH0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 54: TSI0_CH12/PTB19/TPM2_CH1           : 
**                Custom name, Signal name                 : TSI0_CH12/PTB19/TPM2_CH1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 55: ADC0_SE14/TSI0_CH13/PTC0/EXTRG_IN/CMP0_OUT: 
**                Custom name, Signal name                 : ADC0_SE14/TSI0_CH13/PTC0/EXTRG_IN/CMP0_OUT
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 56: ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0: 
**                Custom name, Signal name                 : ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 57: ADC0_SE11/TSI0_CH15/PTC2/I2C1_SDA/TPM0_CH1: 
**                Custom name, Signal name                 : ADC0_SE11/TSI0_CH15/PTC2/I2C1_SDA/TPM0_CH1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 58: PTC3/LLWU_P7/UART1_RX/TPM0_CH2/CLKOUTa: 
**                Custom name, Signal name                 : PTC3/LLWU_P7/UART1_RX/TPM0_CH2/CLKOUTa
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 59: VSS74                              : 
**                Custom name, Signal name                 : VSS74
**              Pin 60: VDD75                              : 
**                Custom name, Signal name                 : VDD75
**              Pin 61: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/TPM0_CH3: 
**                Custom name, Signal name                 : PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/TPM0_CH3
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 62: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT: 
**                Custom name, Signal name                 : PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 63: CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/SPI0_MISO: 
**                Custom name, Signal name                 : CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/SPI0_MISO
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 64: CMP0_IN1/PTC7/SPI0_MISO/SPI0_MOSI  : 
**                Custom name, Signal name                 : CMP0_IN1/PTC7/SPI0_MISO/SPI0_MOSI
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 65: CMP0_IN2/PTC8/I2C0_SCL/TPM0_CH4    : 
**                Custom name, Signal name                 : CMP0_IN2/PTC8/I2C0_SCL/TPM0_CH4
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 66: CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5    : 
**                Custom name, Signal name                 : CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 67: PTC10/I2C1_SCL                     : 
**                Custom name, Signal name                 : PTC10/I2C1_SCL
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 68: PTC11/I2C1_SDA                     : 
**                Custom name, Signal name                 : PTC11/I2C1_SDA
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 69: PTC12/TPM_CLKIN0                   : 
**                Custom name, Signal name                 : PTC12/TPM_CLKIN0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 70: PTC13/TPM_CLKIN1                   : 
**                Custom name, Signal name                 : PTC13/TPM_CLKIN1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 71: PTC16                              : 
**                Custom name, Signal name                 : PTC16
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 72: PTC17                              : 
**                Custom name, Signal name                 : PTC17
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 73: PTD0/SPI0_PCS0/TPM0_CH0            : 
**                Custom name, Signal name                 : PTD0/SPI0_PCS0/TPM0_CH0
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 74: ADC0_SE5b/PTD1/SPI0_SCK/TPM0_CH1   : 
**                Custom name, Signal name                 : ADC0_SE5b/PTD1/SPI0_SCK/TPM0_CH1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 75: PTD2/SPI0_MOSI/UART2_RX/TPM0_CH2/SPI0_MISO: 
**                Custom name, Signal name                 : PTD2/SPI0_MOSI/UART2_RX/TPM0_CH2/SPI0_MISO
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 76: PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI: 
**                Custom name, Signal name                 : PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 77: PTD4/LLWU_P14/SPI1_PCS0/UART2_RX/TPM0_CH4: 
**                Custom name, Signal name                 : PTD4/LLWU_P14/SPI1_PCS0/UART2_RX/TPM0_CH4
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 78: ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5: 
**                Custom name, Signal name                 : ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 79: ADC0_SE7b/PTD6/LLWU_P15/SPI1_MOSI/UART0_RX/SPI1_MISO: 
**                Custom name, Signal name                 : ADC0_SE7b/PTD6/LLWU_P15/SPI1_MOSI/UART0_RX/SPI1_MISO
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 80: PTD7/SPI1_MISO/UART0_TX/SPI1_MOSI  : 
**                Custom name, Signal name                 : PTD7/SPI1_MISO/UART0_TX/SPI1_MOSI
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**          Settings                                       : 
**            Clock gates initialization mode              : SIM HAL (fsl_sim_hal component)
**            Inherited HAL components                     : 
**              fsl_port_hal                               : fsl_port_hal
**              fsl_sim_hal                                : fsl_sim_hal
**              fsl_mcg_hal                                : fsl_mcg_hal
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file pin_mux.c
** @version 1.4
** @brief
**
*/         
/*!
**  @addtogroup pin_mux_module pin_mux module documentation
**  @{
*/         

/* MODULE pin_mux. */


#include "fsl_device_registers.h"
#include "fsl_port_hal.h"
#include "fsl_sim_hal.h"
#include "pin_mux.h"



/*FUNCTION**********************************************************************
*
* Function Name : init_rcm_pins
* Description   : RCM method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_rcm_pins(uint32_t instance)
{
  /* Affects PORTA_PCR20 register */
  PORT_HAL_SetMuxMode(PORTA,20UL,kPortMuxAlt7);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_rcm_pins
* Description   : RCM method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_rcm_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,20UL,kPortPinDisabled);
}

/*FUNCTION**********************************************************************
*
* Function Name : init_swd_pins
* Description   : SWD method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_swd_pins(uint32_t instance)
{
  /* Affects PORTA_PCR0 register */
  PORT_HAL_SetMuxMode(PORTA,0UL,kPortMuxAlt7);
  /* Affects PORTA_PCR3 register */
  PORT_HAL_SetMuxMode(PORTA,3UL,kPortMuxAlt7);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_swd_pins
* Description   : SWD method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_swd_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,0UL,kPortPinDisabled);
  PORT_HAL_SetMuxMode(PORTA,3UL,kPortPinDisabled);
}

/*FUNCTION**********************************************************************
*
* Function Name : init_uart0_pins
* Description   : UART0 method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_uart0_pins(uint32_t instance)
{
  /* Affects PORTA_PCR1 register */
  PORT_HAL_SetMuxMode(PORTA,1UL,kPortMuxAlt2);
  SIM_HAL_SetLpsciRxSrcMode(SIM,UART0_IDX,kSimLpsciRxsrcPin);
  /* Affects PORTA_PCR2 register */
  PORT_HAL_SetMuxMode(PORTA,2UL,kPortMuxAlt2);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_uart0_pins
* Description   : UART0 method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_uart0_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,1UL,kPortPinDisabled);
  PORT_HAL_SetMuxMode(PORTA,2UL,kPortPinDisabled);
}


/* END pin_mux. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
